### ISSUE TITLE
How to use with rector-prefixed?

### ISSUE THREAD

**Issue by vladyslavstartsev** [rectorphp/rector-laravel#1]
Currently, when I try to use it with rector-prefixed

it fails with such error
```
- rector/rector-laravel[dev-main, 0.10.0] require rector/rector ^0.10 -> satisfiable by rector/rector[0.10.0, ..., 0.10.x-dev (alias of dev-main)].
```

**Comment by TomasVotruba** [comment]
Hi, to avoid bigger changes in one release and bothering people with learning too much, these packages bundled inside rector-prefixed. In the future we might split it, but for now it's included.

See:
- https://github.com/rectorphp/rector/blob/e776d753efb775f769916e66b1848d93143f93ae/composer.json#L44-L49

- https://github.com/rectorphp/rector-prefixed/tree/main/vendor/rector
