### ISSUE TITLE
Question - Are there any rules for Laravel 7.x and Laravel 8.x?

### ISSUE THREAD

**Issue by cavo789** [rectorphp/rector-laravel#10]
Hi all

I'm trying to migrate an old Laravel 5.5 application to Laravel 8.x. 

Thanks rector, I can really go faster (**many, many thanks guys!**).

Does something exists to help the migration to Laravel 7x and above? 

I don't know if I'm looking at the right place but it seems the last ruleset is for Laravel 6.x (https://github.com/rectorphp/rector-laravel/blob/main/src/Set/LaravelSetList.php)

**Comment by TomasVotruba** [comment]
Hi, all the available sets are in the class you linked or in this directory:
https://github.com/rectorphp/rector-laravel/tree/main/config/sets

I've bootstraped few rules from the docs, but the rest waits for a Laravel expert to cover this domain :)

**Comment by cavo789** [comment]
Like always, an ultra-fast response. Thanks Tomas!
